## conda requirements for all packages needed to run the scanpy tutorials
# install with:  mamba env create -n scRNAseq2022 -f environment_scRNAseq2022.yml
# then run: source activate scRNAseq2022
name: scRNAseq2022

channels:
### MAIN CONDA CHANNELS ###
 - conda-forge
 - anaconda
 - bioconda
 - defaults
 - r
### ADDITIONAL CONDA CHANNELS ###
 - rdonnelly
 - psi4
 - r_test
 - free
 - fastchan
 - ccordoba12
 - grst
 - Eugene_T
 - letaylor
 - ohsu-comp-bio

dependencies:
### GENERAL LIBRARIES ###
 - r-base=4.1.2
 - rstudio
 - wget
 - compilers
 - notebook
 - jupyter_contrib_nbextensions
 - jupyter_client=6.1.12
 - nbconvert<6
 - pandoc=2.16.2
### R BIOCONDUCTOR PACKAGES ##
 - bioconductor-scater=1.22.0
 - bioconductor-scran=1.22.0
 - bioconductor-singlecellexperiment
 - bioconductor-slingshot
 - bioconductor-tradeseq
# - bioconductor-destiny
 - bioconductor-rhdf5
 - bioconductor-fgsea
 - bioconductor-biomart
 - bioconductor-org.hs.eg.db
 - bioconductor-scdblfinder
 - bioconductor-biocsingular
 - bioconductor-singler
 - bioconductor-batchelor
 - bioconductor-scmap
 - bioconductor-glmgampoi
 - bioconductor-scrnaseq
 - bioconductor-mast
 - bioconductor-dropletutils
### R CRAN PACKAGES ###
 - r-emdbook
 - r-rgl
 - r-plot3d
 - r-scpred
 - r-fastica
 - r-irlba
 - r-pheatmap
 - r-harmony
 - r-msigdbr
 - r-rafalib
 - r-enrichr
 - r-clustree
 - r-devtools
 - r-biocmanager
 - r-rcpphnsw
 - r-dplyr
 - r-igraph
 - r-seurat=4.0.6
 - r-umap
 - r-grr
 - r-hdf5r
 - r-bookdown
 - r-venn
 - r-uwot
 - r-optparse
 - r-fields
 - r-ggraph
 - r-checkmate
 - r-tidygraph
 - r-spam
 - r-stringi
 - r-stringr
 - r-pkgmaker
 - r-l1pack
 - r-nnls
 - r-reshape
 - r-jpeg
### PYTHON LIBRARIES ###
 - python-annoy
 - multicore-tsne
 - requests
 - python-annoy
 - mnnpy
 - scanpy
 - scanorama
 - numba
 - llvmlite
 - python-igraph
 - umap-learn
 - louvain
 - leidenalg
 - matplotlib-venn
 - scrublet
 - gseapy
 - pybiomart
 - morphops
 - pip
 - pip:
   - gsea-api

   
# Manual installation of packages that are not in conda:

# remotes::install_github('chris-mcginnis-ucsf/DoubletFinder', dependencies=FALSE)
# install.packages('clustree', dependencies=FALSE)
# remotes::install_github('satijalab/seurat-data', dependencies=FALSE)
